### ISSUE TITLE
.travis.yml: Update pom.xml versions from any tag which is a valid semver

### ISSUE THREAD

**Issue by lilith** [imazen/sharpen#3]
When TRAVIS_TAG env var is defined, and looks like a semver, use http://mojo.codehaus.org/versions-maven-plugin/examples/set.html to update each pom.xml version prior to the artifact deployment and/or github release.

**Comment by ydanila** [comment]
I implemented this issue in my repo ydanila/sharpen_imazen@721f0e0fcb766600c14c470075a979a9097c9eb0.

**Comment by lilith** [comment]
Thanks!
